language: python3

matrix:
  include:
      os: linux

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $DOCKER_IMAGE
  - docker run $DOCKER_IMAGE /bin/sh -c "find /"

install:
#  - echo yo

script:
  ./bin/env.py 

branches:
  only:
    - master

notifications:
  email: false

